language: python
python:
- 3.6
- 3.5

install: pip install -U tox-travis codecov

script: tox

after_success:
  - codecov

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: hmaarrfk
  password:
      secure: "GDZ23zDDx07diy26rfV21xcW65YuUwE6bPFc/cqyf0XMAdLuqPspwwVQS8CkoTX7rstM6+H2eMmOZBw57hwOhFGK5jNq4dc9DGxt+77TgZcSsdJfFhw04BL6c07Ppgs4S1eTDHhkktjutCPp8tl27m8sagJSqeEOyjPyw3MfH1w0Qs9puBZPs2FkCH8aR39F9MvlfM1jQSB7hhfkQBrxUCAsL9qbM5CPEUdB2v9s/HdALjOuofGUCWY9XNdGuH5tATUtNgldS98/8K+WdiHi0UcTEOek51ctvwu0L2ysD/rgVWwlzsDqXsNQp/pojnRakXDKZOSz2o+498dOY5laEMUVAVIKo+gfHtP00J3nEPSkwsvYJI4bkl5TqrXRkZt6PS8sWsrf2ghU5bZXcIjxlFxurXngcvJXQBpN998GEkJ3LgzVBUWHppvN6ARcp6FN8PZ6I6sFdIUFrP2Qz9PMnZY3o69F57Hp5j3LANwCFCOL13N6EIouaTxV617mWD1YXR2m9CCRcXdpk7jJCKAu11646XD0/dJsIlxY47yWVATshcUf9wbooOG6oEG/NQk1Z0xgTgixT4GdhkevP2wN4teSqQTf7kVOBYgKaQ4GVnBGPw4rx4/hKE/hzVoIzks4ueeKK26I67yhiJUDxhzJKnesS/9/iX8KTo084lJ1VWU="
  on:
    tags: true
    repo: hmaarrfk/wabisabi
    python:
      - 3.5
      - 3.6

